# Используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# Используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

before_install:
- psql -c 'create database tracker;' -U postgres
- psql -c 'create database todo_test;' -U postgres
- psql -c 'create database car_factory_test;' -U postgres

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo.
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту Ponkin.a.v@gmail.com если сборка упала.
notifications:
  email:
    recipients:
      - Ponkin.a.v@gmail.com
    on_success: never # default: change
    on_failure: always # default: always